### PR TITLE
supports multibyte string

### PR DESCRIPTION
**Pull request by renoiv**
I found some incomplete cases.
fixed and checked of 4 test cases.

````
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <script src="https://code.jquery.com/jquery-2.2.1.min.js" type="text/javascript"></script>
        <script src="src/js/jquery.dotdotdot.js" type="text/javascript"></script>
        <title>dotdotdot test cases</title>
        <style>
            .box {
                background-color: #F8F299;
                border: 10px solid #fff;
                padding: 15px 20px 5px 20px;
                margin: 0 0 30px 0;
                box-shadow: 0 0 5px rgba(0, 0, 0, .3);
            }
            .box,
            .box *,
            .box a {
                font-size: 16px;
                line-height: 20px;
                color: #4d4d4d;
            }
            .box.box-3 { height: 80px; }
        </style>
    </head>
    <body>
        <div class="ellipsis box box-3">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</div>


        <!-- 2 spaces. 1st half width. 2nd full width. -->
        <div class="ellipsis box box-3">あいうえお かきくけこ　さしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをんあいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをん。</div>
        <!-- 2 spaces. 1st full width. 2nd half width. -->
        <div class="ellipsis box box-3">あいうえお　かきくけこ さしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをんあいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをん。</div>
        <!-- 1 space. full width only. -->
        <div class="ellipsis box box-3">あいうえお　かきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをんあいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをん。</div>
        <!-- 1 space. half width only. -->
        <div class="ellipsis box box-3">あいうえお かきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをんあいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもらりるれろわをん。</div>


        <script>
        $(document).ready(function() {
            $(".ellipsis").dotdotdot({
                watch: "window"
            });
         });
        </script>
    </body>
</html>
````

### CODE REVIEW

**Comment by FrDH** [comment]
wouldn't replacing a standard space with a non-breaking space break functionality on non-japanese text?

**Comment by jameswilson** [comment]
I think it might actually be the other way around.  In most cases all words are bunched together with no spaces,  so your CSS should already be taking this into account with proper wrapping. now, if you happen to have a space character most browsers will automatically fall back to their “natural” way of breaking lines by looking for a whitespace character first, which is probably not what the designer intends to happen in Japanese.

**Comment by jameswilson** [comment]
Bah.  you said *non-japanese*  my bad, mis-read your question, and agree that you’re correct.  The whitespace character needs to be a per-language configuration option. It’s not an easy problem to solve if you have content in multiple languages on the same page or even in the same paragraphs. Even if the “majority” of your content is CKJ interspersed with a few English words here and there, it’s hard to make a clear-cut answer to whether you want non-breaking spaces or breaking spaces.

**Comment by renoiv** [comment]
I'm sorrry for late response..

> In most cases all words are bunched together with no spaces, so your CSS should already be taking
> this into account with proper wrapping. 

Yes, my problem is this.
In Japanese, space as delimiter is not used often.
for example) This is a difficult problem. = これは難しい問題です。
So, In the case of Japanese, to the basis of the Space it is not a good way.

However, my solution is not a good way.
And I don't have solution yet.
Thank you for the time.

**Comment by jameswilson** [comment]
@renoiv  check out what we're doing on TripAdvisor

https://www.tripadvisor.jp/TripAdvisorInsights

Compare with english version: https://www.tripadvisor.com/TripAdvisorInsights

The white text on the blue slideshow captions as well as the article title links in the card / grid layout below use dotdotdot.  We mix English works and Japanese words mixed together and use CSS tricks like word-wrap to control whitespace / wrapping, etc.

Maybe this will help you?  Not sure.

**Pull request closed without merging**
