### PR TITLE
change space is &nbsp; replace ' '

### PR DESCRIPTION
**Pull request by nfjBill**
Change the Chinese recognition space problem

### CODE REVIEW

**Comment by renoiv** [comment]
+1

**Comment by FrDH** [comment]
That would break functionality with standard spaces, wouldn't it?

**Comment by jameswilson** [comment]
Yup. This should be a configuration option, though (as stated in my other comment on PR #104,  its not entirely clear *how* to expose that configuration, because it highly depends on the content you're trimming.

**Comment by jameswilson** [comment]
I wonder if there is some fast heuristic way to detect the "average unicode range" of the entire string being trimmed,  or maybe come up with some magic ratio of the number of spaces in the string compared to the length of the string that triggers whether to use a nbsp or a plain breaking whitespace.

**Pull request closed without merging**
